### ISSUE TITLE
USER STORY: view variables relevant to price

### ISSUE THREAD

**Issue by knutinator** [knutinator/heritage-housing#1]
- As a client, I want to see visualizations of the most relevant variables correlated to sale price so that I can better understand the relationship between house attributes and sale prices.

### Tasks:

**Pre-process dataset**

- [ ] Identify and clean the data from missing values, duplicates, outliers, etc

**Identify the most relevant variables to sales prices using statistical methods**
- [ ] Perform exploratory data analysis (EDA) on the dataset
- [ ] Identify variables with the highest correlation to sale price using correlation matrices or scatterplots
- [ ] Determine statistical significance of the identified variables using hypothesis testing

**Create data visualizations of the identified variables against sale prices**
- [ ] Choose appropriate visualization techniques for each variable (e.g. scatterplot, line graph, heatmap)
- [ ] Create visualizations that allow users to explore the data
- [ ] Include labels to help users interpret the visualizations
