### ISSUE TITLE
USER STORY: view distribution of attributes

### ISSUE THREAD

**Issue by knutinator** [knutinator/heritage-housing#2]
- As a client, I want to see visualizations of the distribution of house attributes so that I can better understand the range of values for each variable.

### Tasks:

**Create a data visualization of the distribution of house attributes for each variable**
- [ ] Choose appropriate visualization techniques for each variable (e.g. histogram, box plot)
- [ ] Create visualizations that show the distribution of each variable and any outliers or anomalies
- [ ] Include labels to help users interpret the visualizations
