### ISSUE TITLE
USER STORY: view prediction accuracy

### ISSUE THREAD

**Issue by knutinator** [knutinator/heritage-housing#4]
- As a client, I want to be able to test the accuracy of the model on a test set and receive a performance report with an R2 score of at least 0.75 on both the train and test sets.

### Tasks:

**Provide a performance report with an R2 score of at least 0.75 for both the train and test sets**
- [ ] Calculate the R2 score for both the training and test sets
- [ ] Interpret the R2 score and explain the performance of the model
- [ ] Present the performance report in a clear and concise manner
