### ISSUE TITLE
USER STORY: use dashboard easily

### ISSUE THREAD

**Issue by knutinator** [knutinator/heritage-housing#6]
- As a client, I want the dashboard to be user-friendly, intuitive, responsive, and accessible on multiple devices so that I can easily navigate the interface, access the features I need, and use it from anywhere and on any device.

### Tasks:

**Ensure the dashboard is responsive and accessible on multiple devices**
- [ ] Test the dashboard on different devices and screen sizes
- [ ] Implement responsive design techniques such as fluid layout or media queries
- [ ] Ensure the dashboard is accessible to users with disabilities
